package net.lays24mc.xtonesreworkedfabric.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.lays24mc.xtonesreworkedfabric.XtonesReworkedFabric;
import net.lays24mc.xtonesreworkedfabric.block.ModBlocks;
import net.lays24mc.xtonesreworkedfabric.block.custom.*;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class XtonesBlocksGroups {

    public static final ItemGroup xtonesreworkedfabric_group = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(XtonesReworkedFabric.MOD_ID, "xtonestab"),
            FabricItemGroup.builder().displayName(Text.translatable("itemgroup.xtonesreworkedfabric"))
                    .icon(() -> new ItemStack(ModBlocks.XTBlock)).entries((displayContext, entries) -> {
                        /*Entries in creative tab*/
                        // items
//                        entries.add(ModItems.RUBY);

                        // blocks

                        entries.add(ModBlocks.XTBlock);
                        entries.add(ModBlocks.FLAT_LAMP);

                        entries.add(AgonBlocks.AgonBlock);
                        entries.add(AgonBlocks.AgonBlock1);
                        entries.add(AgonBlocks.AgonBlock2);
                        entries.add(AgonBlocks.AgonBlock3);
                        entries.add(AgonBlocks.AgonBlock4);
                        entries.add(AgonBlocks.AgonBlock5);
                        entries.add(AgonBlocks.AgonBlock6);
                        entries.add(AgonBlocks.AgonBlock7);
                        entries.add(AgonBlocks.AgonBlock8);
                        entries.add(AgonBlocks.AgonBlock9);
                        entries.add(AgonBlocks.AgonBlock10);
                        entries.add(AgonBlocks.AgonBlock11);
                        entries.add(AgonBlocks.AgonBlock12);
                        entries.add(AgonBlocks.AgonBlock13);
                        entries.add(AgonBlocks.AgonBlock14);
                        entries.add(AgonBlocks.AgonBlock15);

                        entries.add(AzurBlocks.AzurBlock);
                        entries.add(AzurBlocks.AzurBlock1);
                        entries.add(AzurBlocks.AzurBlock2);
                        entries.add(AzurBlocks.AzurBlock3);
                        entries.add(AzurBlocks.AzurBlock4);
                        entries.add(AzurBlocks.AzurBlock5);
                        entries.add(AzurBlocks.AzurBlock6);
                        entries.add(AzurBlocks.AzurBlock7);
                        entries.add(AzurBlocks.AzurBlock8);
                        entries.add(AzurBlocks.AzurBlock9);
                        entries.add(AzurBlocks.AzurBlock10);
                        entries.add(AzurBlocks.AzurBlock11);
                        entries.add(AzurBlocks.AzurBlock12);
                        entries.add(AzurBlocks.AzurBlock13);
                        entries.add(AzurBlocks.AzurBlock14);
                        entries.add(AzurBlocks.AzurBlock15);

                        entries.add(BittBlocks.BittBlock);
                        entries.add(BittBlocks.BittBlock1);
                        entries.add(BittBlocks.BittBlock2);
                        entries.add(BittBlocks.BittBlock3);
                        entries.add(BittBlocks.BittBlock4);
                        entries.add(BittBlocks.BittBlock5);
                        entries.add(BittBlocks.BittBlock6);
                        entries.add(BittBlocks.BittBlock7);
                        entries.add(BittBlocks.BittBlock8);
                        entries.add(BittBlocks.BittBlock9);
                        entries.add(BittBlocks.BittBlock10);
                        entries.add(BittBlocks.BittBlock11);
                        entries.add(BittBlocks.BittBlock12);
                        entries.add(BittBlocks.BittBlock13);
                        entries.add(BittBlocks.BittBlock14);
                        entries.add(BittBlocks.BittBlock15);

                        entries.add(CrayBlocks.CrayBlock);
                        entries.add(CrayBlocks.CrayBlock1);
                        entries.add(CrayBlocks.CrayBlock2);
                        entries.add(CrayBlocks.CrayBlock3);
                        entries.add(CrayBlocks.CrayBlock4);
                        entries.add(CrayBlocks.CrayBlock5);
                        entries.add(CrayBlocks.CrayBlock6);
                        entries.add(CrayBlocks.CrayBlock7);
                        entries.add(CrayBlocks.CrayBlock8);
                        entries.add(CrayBlocks.CrayBlock9);
                        entries.add(CrayBlocks.CrayBlock10);
                        entries.add(CrayBlocks.CrayBlock11);
                        entries.add(CrayBlocks.CrayBlock12);
                        entries.add(CrayBlocks.CrayBlock13);
                        entries.add(CrayBlocks.CrayBlock14);
                        entries.add(CrayBlocks.CrayBlock15);

                        entries.add(FortBlocks.FortBlock);
                        entries.add(FortBlocks.FortBlock1);
                        entries.add(FortBlocks.FortBlock2);
                        entries.add(FortBlocks.FortBlock3);
                        entries.add(FortBlocks.FortBlock4);
                        entries.add(FortBlocks.FortBlock5);
                        entries.add(FortBlocks.FortBlock6);
                        entries.add(FortBlocks.FortBlock7);
                        entries.add(FortBlocks.FortBlock8);
                        entries.add(FortBlocks.FortBlock9);
                        entries.add(FortBlocks.FortBlock10);
                        entries.add(FortBlocks.FortBlock11);
                        entries.add(FortBlocks.FortBlock12);
                        entries.add(FortBlocks.FortBlock13);
                        entries.add(FortBlocks.FortBlock14);
                        entries.add(FortBlocks.FortBlock15);

                        entries.add(GlaxxBlocks.GlaxxBlock);
                        entries.add(GlaxxBlocks.GlaxxBlock1);
                        entries.add(GlaxxBlocks.GlaxxBlock2);
                        entries.add(GlaxxBlocks.GlaxxBlock3);
                        entries.add(GlaxxBlocks.GlaxxBlock4);
                        entries.add(GlaxxBlocks.GlaxxBlock5);
                        entries.add(GlaxxBlocks.GlaxxBlock6);
                        entries.add(GlaxxBlocks.GlaxxBlock7);
                        entries.add(GlaxxBlocks.GlaxxBlock8);
                        entries.add(GlaxxBlocks.GlaxxBlock9);
                        entries.add(GlaxxBlocks.GlaxxBlock10);
                        entries.add(GlaxxBlocks.GlaxxBlock11);
                        entries.add(GlaxxBlocks.GlaxxBlock12);
                        entries.add(GlaxxBlocks.GlaxxBlock13);
                        entries.add(GlaxxBlocks.GlaxxBlock14);
                        entries.add(GlaxxBlocks.GlaxxBlock15);

                        entries.add(IszmBlocks.IszmBlock);
                        entries.add(IszmBlocks.IszmBlock1);
                        entries.add(IszmBlocks.IszmBlock2);
                        entries.add(IszmBlocks.IszmBlock3);
                        entries.add(IszmBlocks.IszmBlock4);
                        entries.add(IszmBlocks.IszmBlock5);
                        entries.add(IszmBlocks.IszmBlock6);
                        entries.add(IszmBlocks.IszmBlock7);
                        entries.add(IszmBlocks.IszmBlock8);
                        entries.add(IszmBlocks.IszmBlock9);
                        entries.add(IszmBlocks.IszmBlock10);
                        entries.add(IszmBlocks.IszmBlock11);
                        entries.add(IszmBlocks.IszmBlock12);
                        entries.add(IszmBlocks.IszmBlock13);
                        entries.add(IszmBlocks.IszmBlock14);
                        entries.add(IszmBlocks.IszmBlock15);

                        entries.add(JeltBlocks.JeltBlock);
                        entries.add(JeltBlocks.JeltBlock1);
                        entries.add(JeltBlocks.JeltBlock2);
                        entries.add(JeltBlocks.JeltBlock3);
                        entries.add(JeltBlocks.JeltBlock4);
                        entries.add(JeltBlocks.JeltBlock5);
                        entries.add(JeltBlocks.JeltBlock6);
                        entries.add(JeltBlocks.JeltBlock7);
                        entries.add(JeltBlocks.JeltBlock8);
                        entries.add(JeltBlocks.JeltBlock9);
                        entries.add(JeltBlocks.JeltBlock10);
                        entries.add(JeltBlocks.JeltBlock11);
                        entries.add(JeltBlocks.JeltBlock12);
                        entries.add(JeltBlocks.JeltBlock13);
                        entries.add(JeltBlocks.JeltBlock14);
                        entries.add(JeltBlocks.JeltBlock15);

                        entries.add(KorpBlocks.KorpBlock);
                        entries.add(KorpBlocks.KorpBlock1);
                        entries.add(KorpBlocks.KorpBlock2);
                        entries.add(KorpBlocks.KorpBlock3);
                        entries.add(KorpBlocks.KorpBlock4);
                        entries.add(KorpBlocks.KorpBlock5);
                        entries.add(KorpBlocks.KorpBlock6);
                        entries.add(KorpBlocks.KorpBlock7);
                        entries.add(KorpBlocks.KorpBlock8);
                        entries.add(KorpBlocks.KorpBlock9);
                        entries.add(KorpBlocks.KorpBlock10);
                        entries.add(KorpBlocks.KorpBlock11);
                        entries.add(KorpBlocks.KorpBlock12);
                        entries.add(KorpBlocks.KorpBlock13);
                        entries.add(KorpBlocks.KorpBlock14);
                        entries.add(KorpBlocks.KorpBlock15);

                        entries.add(KrypBlocks.KrypBlock);
                        entries.add(KrypBlocks.KrypBlock1);
                        entries.add(KrypBlocks.KrypBlock2);
                        entries.add(KrypBlocks.KrypBlock3);
                        entries.add(KrypBlocks.KrypBlock4);
                        entries.add(KrypBlocks.KrypBlock5);
                        entries.add(KrypBlocks.KrypBlock6);
                        entries.add(KrypBlocks.KrypBlock7);
                        entries.add(KrypBlocks.KrypBlock8);
                        entries.add(KrypBlocks.KrypBlock9);
                        entries.add(KrypBlocks.KrypBlock10);
                        entries.add(KrypBlocks.KrypBlock11);
                        entries.add(KrypBlocks.KrypBlock12);
                        entries.add(KrypBlocks.KrypBlock13);
                        entries.add(KrypBlocks.KrypBlock14);
                        entries.add(KrypBlocks.KrypBlock15);

                        entries.add(LairBlocks.LairBlock);
                        entries.add(LairBlocks.LairBlock1);
                        entries.add(LairBlocks.LairBlock2);
                        entries.add(LairBlocks.LairBlock3);
                        entries.add(LairBlocks.LairBlock4);
                        entries.add(LairBlocks.LairBlock5);
                        entries.add(LairBlocks.LairBlock6);
                        entries.add(LairBlocks.LairBlock7);
                        entries.add(LairBlocks.LairBlock8);
                        entries.add(LairBlocks.LairBlock9);
                        entries.add(LairBlocks.LairBlock10);
                        entries.add(LairBlocks.LairBlock11);
                        entries.add(LairBlocks.LairBlock12);
                        entries.add(LairBlocks.LairBlock13);
                        entries.add(LairBlocks.LairBlock14);
                        entries.add(LairBlocks.LairBlock15);

                        entries.add(LaveBlocks.LaveBlock);
                        entries.add(LaveBlocks.LaveBlock1);
                        entries.add(LaveBlocks.LaveBlock2);
                        entries.add(LaveBlocks.LaveBlock3);
                        entries.add(LaveBlocks.LaveBlock4);
                        entries.add(LaveBlocks.LaveBlock5);
                        entries.add(LaveBlocks.LaveBlock6);
                        entries.add(LaveBlocks.LaveBlock7);
                        entries.add(LaveBlocks.LaveBlock8);
                        entries.add(LaveBlocks.LaveBlock9);
                        entries.add(LaveBlocks.LaveBlock10);
                        entries.add(LaveBlocks.LaveBlock11);
                        entries.add(LaveBlocks.LaveBlock12);
                        entries.add(LaveBlocks.LaveBlock13);
                        entries.add(LaveBlocks.LaveBlock14);
                        entries.add(LaveBlocks.LaveBlock15);

                        entries.add(MintBlocks.MintBlock);
                        entries.add(MintBlocks.MintBlock1);
                        entries.add(MintBlocks.MintBlock2);
                        entries.add(MintBlocks.MintBlock3);
                        entries.add(MintBlocks.MintBlock4);
                        entries.add(MintBlocks.MintBlock5);
                        entries.add(MintBlocks.MintBlock6);
                        entries.add(MintBlocks.MintBlock7);
                        entries.add(MintBlocks.MintBlock8);
                        entries.add(MintBlocks.MintBlock9);
                        entries.add(MintBlocks.MintBlock10);
                        entries.add(MintBlocks.MintBlock11);
                        entries.add(MintBlocks.MintBlock12);
                        entries.add(MintBlocks.MintBlock13);
                        entries.add(MintBlocks.MintBlock14);
                        entries.add(MintBlocks.MintBlock15);

                        entries.add(MystBlocks.MystBlock);
                        entries.add(MystBlocks.MystBlock1);
                        entries.add(MystBlocks.MystBlock2);
                        entries.add(MystBlocks.MystBlock3);
                        entries.add(MystBlocks.MystBlock4);
                        entries.add(MystBlocks.MystBlock5);
                        entries.add(MystBlocks.MystBlock6);
                        entries.add(MystBlocks.MystBlock7);
                        entries.add(MystBlocks.MystBlock8);
                        entries.add(MystBlocks.MystBlock9);
                        entries.add(MystBlocks.MystBlock10);
                        entries.add(MystBlocks.MystBlock11);
                        entries.add(MystBlocks.MystBlock12);
                        entries.add(MystBlocks.MystBlock13);
                        entries.add(MystBlocks.MystBlock14);
                        entries.add(MystBlocks.MystBlock15);

                        entries.add(RedsBlocks.RedsBlock);
                        entries.add(RedsBlocks.RedsBlock1);
                        entries.add(RedsBlocks.RedsBlock2);
                        entries.add(RedsBlocks.RedsBlock3);
                        entries.add(RedsBlocks.RedsBlock4);
                        entries.add(RedsBlocks.RedsBlock5);
                        entries.add(RedsBlocks.RedsBlock6);
                        entries.add(RedsBlocks.RedsBlock7);
                        entries.add(RedsBlocks.RedsBlock8);
                        entries.add(RedsBlocks.RedsBlock9);
                        entries.add(RedsBlocks.RedsBlock10);
                        entries.add(RedsBlocks.RedsBlock11);
                        entries.add(RedsBlocks.RedsBlock12);
                        entries.add(RedsBlocks.RedsBlock13);
                        entries.add(RedsBlocks.RedsBlock14);
                        entries.add(RedsBlocks.RedsBlock15);

                        entries.add(ReedBlocks.ReedBlock);
                        entries.add(ReedBlocks.ReedBlock1);
                        entries.add(ReedBlocks.ReedBlock2);
                        entries.add(ReedBlocks.ReedBlock3);
                        entries.add(ReedBlocks.ReedBlock4);
                        entries.add(ReedBlocks.ReedBlock5);
                        entries.add(ReedBlocks.ReedBlock6);
                        entries.add(ReedBlocks.ReedBlock7);
                        entries.add(ReedBlocks.ReedBlock8);
                        entries.add(ReedBlocks.ReedBlock9);
                        entries.add(ReedBlocks.ReedBlock10);
                        entries.add(ReedBlocks.ReedBlock11);
                        entries.add(ReedBlocks.ReedBlock12);
                        entries.add(ReedBlocks.ReedBlock13);
                        entries.add(ReedBlocks.ReedBlock14);
                        entries.add(ReedBlocks.ReedBlock15);

                        entries.add(RoenBlocks.RoenBlock);
                        entries.add(RoenBlocks.RoenBlock1);
                        entries.add(RoenBlocks.RoenBlock2);
                        entries.add(RoenBlocks.RoenBlock3);
                        entries.add(RoenBlocks.RoenBlock4);
                        entries.add(RoenBlocks.RoenBlock5);
                        entries.add(RoenBlocks.RoenBlock6);
                        entries.add(RoenBlocks.RoenBlock7);
                        entries.add(RoenBlocks.RoenBlock8);
                        entries.add(RoenBlocks.RoenBlock9);
                        entries.add(RoenBlocks.RoenBlock10);
                        entries.add(RoenBlocks.RoenBlock11);
                        entries.add(RoenBlocks.RoenBlock12);
                        entries.add(RoenBlocks.RoenBlock13);
                        entries.add(RoenBlocks.RoenBlock14);
                        entries.add(RoenBlocks.RoenBlock15);

                        entries.add(SolsBlocks.SolsBlock);
                        entries.add(SolsBlocks.SolsBlock1);
                        entries.add(SolsBlocks.SolsBlock2);
                        entries.add(SolsBlocks.SolsBlock3);
                        entries.add(SolsBlocks.SolsBlock4);
                        entries.add(SolsBlocks.SolsBlock5);
                        entries.add(SolsBlocks.SolsBlock6);
                        entries.add(SolsBlocks.SolsBlock7);
                        entries.add(SolsBlocks.SolsBlock8);
                        entries.add(SolsBlocks.SolsBlock9);
                        entries.add(SolsBlocks.SolsBlock10);
                        entries.add(SolsBlocks.SolsBlock11);
                        entries.add(SolsBlocks.SolsBlock12);
                        entries.add(SolsBlocks.SolsBlock13);
                        entries.add(SolsBlocks.SolsBlock14);
                        entries.add(SolsBlocks.SolsBlock15);

                        entries.add(SyncBlocks.SyncBlock);
                        entries.add(SyncBlocks.SyncBlock1);
                        entries.add(SyncBlocks.SyncBlock2);
                        entries.add(SyncBlocks.SyncBlock3);
                        entries.add(SyncBlocks.SyncBlock4);
                        entries.add(SyncBlocks.SyncBlock5);
                        entries.add(SyncBlocks.SyncBlock6);
                        entries.add(SyncBlocks.SyncBlock7);
                        entries.add(SyncBlocks.SyncBlock8);
                        entries.add(SyncBlocks.SyncBlock9);
                        entries.add(SyncBlocks.SyncBlock10);
                        entries.add(SyncBlocks.SyncBlock11);
                        entries.add(SyncBlocks.SyncBlock12);
                        entries.add(SyncBlocks.SyncBlock13);
                        entries.add(SyncBlocks.SyncBlock14);
                        entries.add(SyncBlocks.SyncBlock15);

                        entries.add(TankBlocks.TankBlock);
                        entries.add(TankBlocks.TankBlock1);
                        entries.add(TankBlocks.TankBlock2);
                        entries.add(TankBlocks.TankBlock3);
                        entries.add(TankBlocks.TankBlock4);
                        entries.add(TankBlocks.TankBlock5);
                        entries.add(TankBlocks.TankBlock6);
                        entries.add(TankBlocks.TankBlock7);
                        entries.add(TankBlocks.TankBlock8);
                        entries.add(TankBlocks.TankBlock9);
                        entries.add(TankBlocks.TankBlock10);
                        entries.add(TankBlocks.TankBlock11);
                        entries.add(TankBlocks.TankBlock12);
                        entries.add(TankBlocks.TankBlock13);
                        entries.add(TankBlocks.TankBlock14);
                        entries.add(TankBlocks.TankBlock15);

                        entries.add(VectBlocks.VectBlock);
                        entries.add(VectBlocks.VectBlock1);
                        entries.add(VectBlocks.VectBlock2);
                        entries.add(VectBlocks.VectBlock3);
                        entries.add(VectBlocks.VectBlock4);
                        entries.add(VectBlocks.VectBlock5);
                        entries.add(VectBlocks.VectBlock6);
                        entries.add(VectBlocks.VectBlock7);
                        entries.add(VectBlocks.VectBlock8);
                        entries.add(VectBlocks.VectBlock9);
                        entries.add(VectBlocks.VectBlock10);
                        entries.add(VectBlocks.VectBlock11);
                        entries.add(VectBlocks.VectBlock12);
                        entries.add(VectBlocks.VectBlock13);
                        entries.add(VectBlocks.VectBlock14);
                        entries.add(VectBlocks.VectBlock15);

                        entries.add(VenaBlocks.VenaBlock);
                        entries.add(VenaBlocks.VenaBlock1);
                        entries.add(VenaBlocks.VenaBlock2);
                        entries.add(VenaBlocks.VenaBlock3);
                        entries.add(VenaBlocks.VenaBlock4);
                        entries.add(VenaBlocks.VenaBlock5);
                        entries.add(VenaBlocks.VenaBlock6);
                        entries.add(VenaBlocks.VenaBlock7);
                        entries.add(VenaBlocks.VenaBlock8);
                        entries.add(VenaBlocks.VenaBlock9);
                        entries.add(VenaBlocks.VenaBlock10);
                        entries.add(VenaBlocks.VenaBlock11);
                        entries.add(VenaBlocks.VenaBlock12);
                        entries.add(VenaBlocks.VenaBlock13);
                        entries.add(VenaBlocks.VenaBlock14);
                        entries.add(VenaBlocks.VenaBlock15);

                        entries.add(ZaneBlocks.ZaneBlock);
                        entries.add(ZaneBlocks.ZaneBlock1);
                        entries.add(ZaneBlocks.ZaneBlock2);
                        entries.add(ZaneBlocks.ZaneBlock3);
                        entries.add(ZaneBlocks.ZaneBlock4);
                        entries.add(ZaneBlocks.ZaneBlock5);
                        entries.add(ZaneBlocks.ZaneBlock6);
                        entries.add(ZaneBlocks.ZaneBlock7);
                        entries.add(ZaneBlocks.ZaneBlock8);
                        entries.add(ZaneBlocks.ZaneBlock9);
                        entries.add(ZaneBlocks.ZaneBlock10);
                        entries.add(ZaneBlocks.ZaneBlock11);
                        entries.add(ZaneBlocks.ZaneBlock12);
                        entries.add(ZaneBlocks.ZaneBlock13);
                        entries.add(ZaneBlocks.ZaneBlock14);
                        entries.add(ZaneBlocks.ZaneBlock15);

                        entries.add(ZechBlocks.ZechBlock);
                        entries.add(ZechBlocks.ZechBlock1);
                        entries.add(ZechBlocks.ZechBlock2);
                        entries.add(ZechBlocks.ZechBlock3);
                        entries.add(ZechBlocks.ZechBlock4);
                        entries.add(ZechBlocks.ZechBlock5);
                        entries.add(ZechBlocks.ZechBlock6);
                        entries.add(ZechBlocks.ZechBlock7);
                        entries.add(ZechBlocks.ZechBlock8);
                        entries.add(ZechBlocks.ZechBlock9);
                        entries.add(ZechBlocks.ZechBlock10);
                        entries.add(ZechBlocks.ZechBlock11);
                        entries.add(ZechBlocks.ZechBlock12);
                        entries.add(ZechBlocks.ZechBlock13);
                        entries.add(ZechBlocks.ZechBlock14);
                        entries.add(ZechBlocks.ZechBlock15);

                        entries.add(ZestBlocks.ZestBlock);
                        entries.add(ZestBlocks.ZestBlock1);
                        entries.add(ZestBlocks.ZestBlock2);
                        entries.add(ZestBlocks.ZestBlock3);
                        entries.add(ZestBlocks.ZestBlock4);
                        entries.add(ZestBlocks.ZestBlock5);
                        entries.add(ZestBlocks.ZestBlock6);
                        entries.add(ZestBlocks.ZestBlock7);
                        entries.add(ZestBlocks.ZestBlock8);
                        entries.add(ZestBlocks.ZestBlock9);
                        entries.add(ZestBlocks.ZestBlock10);
                        entries.add(ZestBlocks.ZestBlock11);
                        entries.add(ZestBlocks.ZestBlock12);
                        entries.add(ZestBlocks.ZestBlock13);
                        entries.add(ZestBlocks.ZestBlock14);
                        entries.add(ZestBlocks.ZestBlock15);

                        entries.add(ZetaBlocks.ZetaBlock);
                        entries.add(ZetaBlocks.ZetaBlock1);
                        entries.add(ZetaBlocks.ZetaBlock2);
                        entries.add(ZetaBlocks.ZetaBlock3);
                        entries.add(ZetaBlocks.ZetaBlock4);
                        entries.add(ZetaBlocks.ZetaBlock5);
                        entries.add(ZetaBlocks.ZetaBlock6);
                        entries.add(ZetaBlocks.ZetaBlock7);
                        entries.add(ZetaBlocks.ZetaBlock8);
                        entries.add(ZetaBlocks.ZetaBlock9);
                        entries.add(ZetaBlocks.ZetaBlock10);
                        entries.add(ZetaBlocks.ZetaBlock11);
                        entries.add(ZetaBlocks.ZetaBlock12);
                        entries.add(ZetaBlocks.ZetaBlock13);
                        entries.add(ZetaBlocks.ZetaBlock14);
                        entries.add(ZetaBlocks.ZetaBlock15);

                        entries.add(ZionBlocks.ZionBlock);
                        entries.add(ZionBlocks.ZionBlock1);
                        entries.add(ZionBlocks.ZionBlock2);
                        entries.add(ZionBlocks.ZionBlock3);
                        entries.add(ZionBlocks.ZionBlock4);
                        entries.add(ZionBlocks.ZionBlock5);
                        entries.add(ZionBlocks.ZionBlock6);
                        entries.add(ZionBlocks.ZionBlock7);
                        entries.add(ZionBlocks.ZionBlock8);
                        entries.add(ZionBlocks.ZionBlock9);
                        entries.add(ZionBlocks.ZionBlock10);
                        entries.add(ZionBlocks.ZionBlock11);
                        entries.add(ZionBlocks.ZionBlock12);
                        entries.add(ZionBlocks.ZionBlock13);
                        entries.add(ZionBlocks.ZionBlock14);
                        entries.add(ZionBlocks.ZionBlock15);

                        entries.add(ZkulBlocks.ZkulBlock);
                        entries.add(ZkulBlocks.ZkulBlock1);
                        entries.add(ZkulBlocks.ZkulBlock2);
                        entries.add(ZkulBlocks.ZkulBlock3);
                        entries.add(ZkulBlocks.ZkulBlock4);
                        entries.add(ZkulBlocks.ZkulBlock5);
                        entries.add(ZkulBlocks.ZkulBlock6);
                        entries.add(ZkulBlocks.ZkulBlock7);
                        entries.add(ZkulBlocks.ZkulBlock8);
                        entries.add(ZkulBlocks.ZkulBlock9);
                        entries.add(ZkulBlocks.ZkulBlock10);
                        entries.add(ZkulBlocks.ZkulBlock11);
                        entries.add(ZkulBlocks.ZkulBlock12);
                        entries.add(ZkulBlocks.ZkulBlock13);
                        entries.add(ZkulBlocks.ZkulBlock14);
                        entries.add(ZkulBlocks.ZkulBlock15);

                        entries.add(ZoeaBlocks.ZoeaBlock);
                        entries.add(ZoeaBlocks.ZoeaBlock1);
                        entries.add(ZoeaBlocks.ZoeaBlock2);
                        entries.add(ZoeaBlocks.ZoeaBlock3);
                        entries.add(ZoeaBlocks.ZoeaBlock4);
                        entries.add(ZoeaBlocks.ZoeaBlock5);
                        entries.add(ZoeaBlocks.ZoeaBlock6);
                        entries.add(ZoeaBlocks.ZoeaBlock7);
                        entries.add(ZoeaBlocks.ZoeaBlock8);
                        entries.add(ZoeaBlocks.ZoeaBlock9);
                        entries.add(ZoeaBlocks.ZoeaBlock10);
                        entries.add(ZoeaBlocks.ZoeaBlock11);
                        entries.add(ZoeaBlocks.ZoeaBlock12);
                        entries.add(ZoeaBlocks.ZoeaBlock13);
                        entries.add(ZoeaBlocks.ZoeaBlock14);
                        entries.add(ZoeaBlocks.ZoeaBlock15);

                        entries.add(ZomeBlocks.ZomeBlock);
                        entries.add(ZomeBlocks.ZomeBlock1);
                        entries.add(ZomeBlocks.ZomeBlock2);
                        entries.add(ZomeBlocks.ZomeBlock3);
                        entries.add(ZomeBlocks.ZomeBlock4);
                        entries.add(ZomeBlocks.ZomeBlock5);
                        entries.add(ZomeBlocks.ZomeBlock6);
                        entries.add(ZomeBlocks.ZomeBlock7);
                        entries.add(ZomeBlocks.ZomeBlock8);
                        entries.add(ZomeBlocks.ZomeBlock9);
                        entries.add(ZomeBlocks.ZomeBlock10);
                        entries.add(ZomeBlocks.ZomeBlock11);
                        entries.add(ZomeBlocks.ZomeBlock12);
                        entries.add(ZomeBlocks.ZomeBlock13);
                        entries.add(ZomeBlocks.ZomeBlock14);
                        entries.add(ZomeBlocks.ZomeBlock15);

                        entries.add(ZoneBlocks.ZoneBlock);
                        entries.add(ZoneBlocks.ZoneBlock1);
                        entries.add(ZoneBlocks.ZoneBlock2);
                        entries.add(ZoneBlocks.ZoneBlock3);
                        entries.add(ZoneBlocks.ZoneBlock4);
                        entries.add(ZoneBlocks.ZoneBlock5);
                        entries.add(ZoneBlocks.ZoneBlock6);
                        entries.add(ZoneBlocks.ZoneBlock7);
                        entries.add(ZoneBlocks.ZoneBlock8);
                        entries.add(ZoneBlocks.ZoneBlock9);
                        entries.add(ZoneBlocks.ZoneBlock10);
                        entries.add(ZoneBlocks.ZoneBlock11);
                        entries.add(ZoneBlocks.ZoneBlock12);
                        entries.add(ZoneBlocks.ZoneBlock13);
                        entries.add(ZoneBlocks.ZoneBlock14);
                        entries.add(ZoneBlocks.ZoneBlock15);

                        entries.add(ZorgBlocks.ZorgBlock);
                        entries.add(ZorgBlocks.ZorgBlock1);
                        entries.add(ZorgBlocks.ZorgBlock2);
                        entries.add(ZorgBlocks.ZorgBlock3);
                        entries.add(ZorgBlocks.ZorgBlock4);
                        entries.add(ZorgBlocks.ZorgBlock5);
                        entries.add(ZorgBlocks.ZorgBlock6);
                        entries.add(ZorgBlocks.ZorgBlock7);
                        entries.add(ZorgBlocks.ZorgBlock8);
                        entries.add(ZorgBlocks.ZorgBlock9);
                        entries.add(ZorgBlocks.ZorgBlock10);
                        entries.add(ZorgBlocks.ZorgBlock11);
                        entries.add(ZorgBlocks.ZorgBlock12);
                        entries.add(ZorgBlocks.ZorgBlock13);
                        entries.add(ZorgBlocks.ZorgBlock14);
                        entries.add(ZorgBlocks.ZorgBlock15);

                        entries.add(ZtylBlocks.ZtylBlock);
                        entries.add(ZtylBlocks.ZtylBlock1);
                        entries.add(ZtylBlocks.ZtylBlock2);
                        entries.add(ZtylBlocks.ZtylBlock3);
                        entries.add(ZtylBlocks.ZtylBlock4);
                        entries.add(ZtylBlocks.ZtylBlock5);
                        entries.add(ZtylBlocks.ZtylBlock6);
                        entries.add(ZtylBlocks.ZtylBlock7);
                        entries.add(ZtylBlocks.ZtylBlock8);
                        entries.add(ZtylBlocks.ZtylBlock9);
                        entries.add(ZtylBlocks.ZtylBlock10);
                        entries.add(ZtylBlocks.ZtylBlock11);
                        entries.add(ZtylBlocks.ZtylBlock12);
                        entries.add(ZtylBlocks.ZtylBlock13);
                        entries.add(ZtylBlocks.ZtylBlock14);
                        entries.add(ZtylBlocks.ZtylBlock15);

                        entries.add(ZythBlocks.ZythBlock);
                        entries.add(ZythBlocks.ZythBlock1);
                        entries.add(ZythBlocks.ZythBlock2);
                        entries.add(ZythBlocks.ZythBlock3);
                        entries.add(ZythBlocks.ZythBlock4);
                        entries.add(ZythBlocks.ZythBlock5);
                        entries.add(ZythBlocks.ZythBlock6);
                        entries.add(ZythBlocks.ZythBlock7);
                        entries.add(ZythBlocks.ZythBlock8);
                        entries.add(ZythBlocks.ZythBlock9);
                        entries.add(ZythBlocks.ZythBlock10);
                        entries.add(ZythBlocks.ZythBlock11);
                        entries.add(ZythBlocks.ZythBlock12);
                        entries.add(ZythBlocks.ZythBlock13);
                        entries.add(ZythBlocks.ZythBlock14);
                        entries.add(ZythBlocks.ZythBlock15);

                    }).build());
    
    public static void registerItemGroup(){
        XtonesReworkedFabric.LOGGER.info("Registering item group for " + XtonesReworkedFabric.MOD_ID);
    }
}
